"""Initial migration

Revision ID: c2565a39c19d
Revises: 96e686f1961c
Create Date: 2024-09-28 23:51:46.418438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2565a39c19d'
down_revision: Union[str, None] = '96e686f1961c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_medications')
    op.drop_index('ix_medications_id', table_name='medications')
    op.drop_table('medications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('medications_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('side_effects', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='medications_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_medications_id', 'medications', ['id'], unique=False)
    op.create_table('user_medications',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medications_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['medications_id'], ['medications.id'], name='user_medications_medications_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_medications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'medications_id', name='user_medications_pkey')
    )
    # ### end Alembic commands ###
