# Drug Information
drug_info_A = [
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Pyrethrin and Piperonyl Butoxide Topical, Link: https://medlineplus.gov/druginfo/meds/a601105.html',
    'Drug Name: Antipyrine-Benzocaine Otic, Link: https://medlineplus.gov/druginfo/meds/a607073.html',
    'Drug Name: Hydrocortisone Injection, Link: https://medlineplus.gov/druginfo/meds/a682871.html',
    'Drug Name: Methylprednisolone Injection, Link: https://medlineplus.gov/druginfo/meds/a601157.html',
    'Drug Name: Chlordiazepoxide, Link: https://medlineplus.gov/druginfo/meds/a682078.html',
    'Drug Name: Tetrahydrozoline Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a682563.html',
    'Drug Name: Abacavir, Link: https://medlineplus.gov/druginfo/meds/a699012.html',
    'Drug Name: Abacavir, Dolutegravir, and Lamivudine, Link: https://medlineplus.gov/druginfo/meds/a617015.html',
    'Drug Name: Abacavir, Lamivudine, and Zidovudine, Link: https://medlineplus.gov/druginfo/meds/a616051.html',
    'Drug Name: Abaloparatide Injection, Link: https://medlineplus.gov/druginfo/meds/a617038.html',
    'Drug Name: Abatacept Injection, Link: https://medlineplus.gov/druginfo/meds/a606016.html',
    'Drug Name: Idecabtagene Vicleucel Injection, Link: https://medlineplus.gov/druginfo/meds/a621024.html',
    'Drug Name: Amphotericin B Lipid Complex Injection, Link: https://medlineplus.gov/druginfo/meds/a601132.html',
    'Drug Name: Abemaciclib, Link: https://medlineplus.gov/druginfo/meds/a617049.html',
    'Drug Name: Aripiprazole, Link: https://medlineplus.gov/druginfo/meds/a603012.html',
    'Drug Name: Aripiprazole Injection, Link: https://medlineplus.gov/druginfo/meds/a615048.html',
    'Drug Name: Aripiprazole Injection, Link: https://medlineplus.gov/druginfo/meds/a615048.html',
    'Drug Name: Aripiprazole Injection, Link: https://medlineplus.gov/druginfo/meds/a615048.html',
    'Drug Name: Aripiprazole, Link: https://medlineplus.gov/druginfo/meds/a603012.html',
    'Drug Name: Abiraterone, Link: https://medlineplus.gov/druginfo/meds/a611046.html',
    'Drug Name: Methotrexate Injection, Link: https://medlineplus.gov/druginfo/meds/a682018.html',
    'Drug Name: AbobotulinumtoxinA Injection, Link: https://medlineplus.gov/druginfo/meds/a609035.html',
    'Drug Name: Paclitaxel (with albumin) Injection, Link: https://medlineplus.gov/druginfo/meds/a619008.html',
    'Drug Name: Adalimumab Injection, Link: https://medlineplus.gov/druginfo/meds/a603010.html',
    'Drug Name: Abrocitinib, Link: https://medlineplus.gov/druginfo/meds/a622008.html',
    'Drug Name: RSV (Respiratory Syncytial Virus) Vaccine, Link: https://medlineplus.gov/druginfo/meds/a623035.html',
    'Drug Name: Lidocaine Transdermal Patch, Link: https://medlineplus.gov/druginfo/meds/a603026.html',
    'Drug Name: Isotretinoin, Link: https://medlineplus.gov/druginfo/meds/a681043.html',
    'Drug Name: Fentanyl, Link: https://medlineplus.gov/druginfo/meds/a605043.html',
    'Drug Name: Acalabrutinib, Link: https://medlineplus.gov/druginfo/meds/a618004.html',
    'Drug Name: Acamprosate, Link: https://medlineplus.gov/druginfo/meds/a604028.html',
    'Drug Name: Benzoyl Peroxide Topical, Link: https://medlineplus.gov/druginfo/meds/a601026.html',
    'Drug Name: Clindamycin and Benzoyl Peroxide Topical, Link: https://medlineplus.gov/druginfo/meds/a603021.html',
    'Drug Name: Acarbose, Link: https://medlineplus.gov/druginfo/meds/a696015.html',
    'Drug Name: Zafirlukast, Link: https://medlineplus.gov/druginfo/meds/a697007.html',
    'Drug Name: Somatropin, Link: https://medlineplus.gov/druginfo/meds/a622022.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Pseudoephedrine, Link: https://medlineplus.gov/druginfo/meds/a682619.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Albuterol Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a682145.html',
    'Drug Name: Quinapril, Link: https://medlineplus.gov/druginfo/meds/a692026.html',
    'Drug Name: Theophylline, Link: https://medlineplus.gov/druginfo/meds/a681006.html',
    'Drug Name: Hydrochlorothiazide, Link: https://medlineplus.gov/druginfo/meds/a682571.html',
    'Drug Name: Quinapril, Link: https://medlineplus.gov/druginfo/meds/a692026.html',
    'Drug Name: Isotretinoin, Link: https://medlineplus.gov/druginfo/meds/a681043.html',
    'Drug Name: Acebutolol, Link: https://medlineplus.gov/druginfo/meds/a687003.html',
    'Drug Name: Perindopril, Link: https://medlineplus.gov/druginfo/meds/a602017.html',
    'Drug Name: Acetaminophen Rectal, Link: https://medlineplus.gov/druginfo/meds/a621016.html',
    'Drug Name: Acetaminophen, Link: https://medlineplus.gov/druginfo/meds/a681004.html',
    'Drug Name: Acetaminophen and Codeine, Link: https://medlineplus.gov/druginfo/meds/a601005.html',
    'Drug Name: Acetaminophen Injection, Link: https://medlineplus.gov/druginfo/meds/a611019.html',
    'Drug Name: Acetaminophen Rectal, Link: https://medlineplus.gov/druginfo/meds/a621016.html',
    'Drug Name: Acetaminophen, Butalbital, and Caffeine, Link: https://medlineplus.gov/druginfo/meds/a601009.html',
    'Drug Name: Acetazolamide, Link: https://medlineplus.gov/druginfo/meds/a682756.html',
    'Drug Name: Medroxyprogesterone Injection, Link: https://medlineplus.gov/druginfo/meds/a604039.html',
    'Drug Name: Medroxyprogesterone, Link: https://medlineplus.gov/druginfo/meds/a682470.html',
    'Drug Name: Acetylcysteine Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a615021.html',
    'Drug Name: Aspirin Rectal, Link: https://medlineplus.gov/druginfo/meds/a621021.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Tetracycline, Link: https://medlineplus.gov/druginfo/meds/a682098.html',
    'Drug Name: Rabeprazole, Link: https://medlineplus.gov/druginfo/meds/a699060.html',
    'Drug Name: Rabeprazole, Link: https://medlineplus.gov/druginfo/meds/a699060.html',
    'Drug Name: Acitretin, Link: https://medlineplus.gov/druginfo/meds/a601010.html',
    'Drug Name: Aclidinium Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a613001.html',
    'Drug Name: Benzoyl Peroxide Topical, Link: https://medlineplus.gov/druginfo/meds/a601026.html',
    'Drug Name: Benzoyl Peroxide Topical, Link: https://medlineplus.gov/druginfo/meds/a601026.html',
    'Drug Name: Fluoride, Link: https://medlineplus.gov/druginfo/meds/a682727.html',
    'Drug Name: Acetaminophen, Link: https://medlineplus.gov/druginfo/meds/a681004.html',
    'Drug Name: Tocilizumab Injection, Link: https://medlineplus.gov/druginfo/meds/a611004.html',
    'Drug Name: Corticotropin, Repository Injection, Link: https://medlineplus.gov/druginfo/meds/a613006.html',
    'Drug Name: Haemophilus influenzae type b (Hib) Vaccine, Link: https://medlineplus.gov/druginfo/meds/a607015.html',
    'Drug Name: Doxycycline, Link: https://medlineplus.gov/druginfo/meds/a682063.html',
    'Drug Name: Doxycycline, Link: https://medlineplus.gov/druginfo/meds/a682063.html',
    'Drug Name: Chlorpheniramine, Link: https://medlineplus.gov/druginfo/meds/a682543.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Chlorpheniramine, Link: https://medlineplus.gov/druginfo/meds/a682543.html',
    'Drug Name: Ursodiol, Link: https://medlineplus.gov/druginfo/meds/a699047.html',
    'Drug Name: Interferon Gamma-1b Injection, Link: https://medlineplus.gov/druginfo/meds/a601152.html',
    'Drug Name: Dactinomycin, Link: https://medlineplus.gov/druginfo/meds/a682224.html',
    'Drug Name: Fentanyl, Link: https://medlineplus.gov/druginfo/meds/a605043.html',
    'Drug Name: Estrogen and Progestin (Hormone Replacement Therapy), Link: https://medlineplus.gov/druginfo/meds/a601041.html',
    'Drug Name: Risedronate, Link: https://medlineplus.gov/druginfo/meds/a601247.html',
    'Drug Name: Risedronate, Link: https://medlineplus.gov/druginfo/meds/a601247.html',
    'Drug Name: Metformin, Link: https://medlineplus.gov/druginfo/meds/a696005.html',
    'Drug Name: Pioglitazone, Link: https://medlineplus.gov/druginfo/meds/a699016.html',
    'Drug Name: Pioglitazone, Link: https://medlineplus.gov/druginfo/meds/a699016.html',
    'Drug Name: Pioglitazone, Link: https://medlineplus.gov/druginfo/meds/a699016.html',
    'Drug Name: Ketoprofen, Link: https://medlineplus.gov/druginfo/meds/a686014.html',
    'Drug Name: Ketorolac Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a601241.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Ketorolac Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a601241.html',
    'Drug Name: Acyclovir Topical, Link: https://medlineplus.gov/druginfo/meds/a606001.html',
    'Drug Name: Acyclovir, Link: https://medlineplus.gov/druginfo/meds/a681045.html',
    'Drug Name: Acyclovir Topical, Link: https://medlineplus.gov/druginfo/meds/a606001.html',
    'Drug Name: Acyclovir, Link: https://medlineplus.gov/druginfo/meds/a681045.html',
    'Drug Name: Acyclovir, Link: https://medlineplus.gov/druginfo/meds/a681045.html',
    'Drug Name: Acyclovir Buccal, Link: https://medlineplus.gov/druginfo/meds/a619042.html',
    'Drug Name: Acyclovir Injection, Link: https://medlineplus.gov/druginfo/meds/a681036.html',
    'Drug Name: Acyclovir Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a619029.html',
    'Drug Name: Acyclovir Topical, Link: https://medlineplus.gov/druginfo/meds/a606001.html',
    'Drug Name: Dapsone Topical, Link: https://medlineplus.gov/druginfo/meds/a616045.html',
    'Drug Name: COVID-19 Vaccine, Viral Vector (Janssen [Johnson and Johnson]), Link: https://medlineplus.gov/druginfo/meds/a621007.html',
    'Drug Name: Tetanus, Diphtheria, Pertussis (Tdap) Vaccine, Link: https://medlineplus.gov/druginfo/meds/a607027.html',
    'Drug Name: Adagrasib, Link: https://medlineplus.gov/druginfo/meds/a623003.html',
    'Drug Name: Crizanlizumab-tmca Injection, Link: https://medlineplus.gov/druginfo/meds/a620010.html',
    'Drug Name: Nifedipine, Link: https://medlineplus.gov/druginfo/meds/a684028.html',
    'Drug Name: Nifedipine, Link: https://medlineplus.gov/druginfo/meds/a684028.html',
    'Drug Name: Adalimumab Injection, Link: https://medlineplus.gov/druginfo/meds/a603010.html',
    'Drug Name: Amantadine, Link: https://medlineplus.gov/druginfo/meds/a682064.html',
    'Drug Name: Adapalene, Link: https://medlineplus.gov/druginfo/meds/a604001.html',
    'Drug Name: Tralokinumab-ldrm injection, Link: https://medlineplus.gov/druginfo/meds/a622011.html',
    'Drug Name: Brentuximab Vedotin Injection, Link: https://medlineplus.gov/druginfo/meds/a611052.html',
    'Drug Name: Tadalafil, Link: https://medlineplus.gov/druginfo/meds/a604008.html',
    'Drug Name: Ibuprofen, Link: https://medlineplus.gov/druginfo/meds/a682159.html',
    'Drug Name: Dextroamphetamine and Amphetamine, Link: https://medlineplus.gov/druginfo/meds/a601234.html',
    'Drug Name: Dextroamphetamine and Amphetamine, Link: https://medlineplus.gov/druginfo/meds/a601234.html',
    'Drug Name: Flibanserin, Link: https://medlineplus.gov/druginfo/meds/a615040.html',
    'Drug Name: Adefovir, Link: https://medlineplus.gov/druginfo/meds/a605024.html',
    'Drug Name: Riociguat, Link: https://medlineplus.gov/druginfo/meds/a615005.html',
    'Drug Name: COVID-19 Vaccine, Viral Vector (Janssen [Johnson and Johnson]), Link: https://medlineplus.gov/druginfo/meds/a621007.html',
    'Drug Name: COVID-19 Vaccine, Viral Vector (Janssen [Johnson and Johnson]), Link: https://medlineplus.gov/druginfo/meds/a621007.html',
    'Drug Name: Methylphenidate, Link: https://medlineplus.gov/druginfo/meds/a682188.html',
    'Drug Name: Phentermine, Link: https://medlineplus.gov/druginfo/meds/a682187.html',
    'Drug Name: Lixisenatide Injection, Link: https://medlineplus.gov/druginfo/meds/a617005.html',
    'Drug Name: Insulin Lispro Injection, Link: https://medlineplus.gov/druginfo/meds/a697021.html',
    'Drug Name: Ado-trastuzumab Emtansine Injection, Link: https://medlineplus.gov/druginfo/meds/a613031.html',
    'Drug Name: Pamidronate Injection, Link: https://medlineplus.gov/druginfo/meds/a601163.html',
    'Drug Name: Epinephrine Injection, Link: https://medlineplus.gov/druginfo/meds/a603002.html',
    'Drug Name: Epinephrine Injection, Link: https://medlineplus.gov/druginfo/meds/a603002.html',
    'Drug Name: Doxorubicin, Link: https://medlineplus.gov/druginfo/meds/a682221.html',
    'Drug Name: Fluorouracil Injection, Link: https://medlineplus.gov/druginfo/meds/a682708.html',
    'Drug Name: Nadofaragene firadenovec-vncg Intravesical, Link: https://medlineplus.gov/druginfo/meds/a623062.html',
    'Drug Name: Aducanumab-avwa Injection, Link: https://medlineplus.gov/druginfo/meds/a621033.html',
    'Drug Name: Aducanumab-avwa Injection, Link: https://medlineplus.gov/druginfo/meds/a621033.html',
    'Drug Name: Guaifenesin, Link: https://medlineplus.gov/druginfo/meds/a682494.html',
    'Drug Name: Guaifenesin, Link: https://medlineplus.gov/druginfo/meds/a682494.html',
    'Drug Name: Fluticasone and Salmeterol Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a699063.html',
    'Drug Name: Fluticasone and Salmeterol Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a699063.html',
    'Drug Name: Fluoride, Link: https://medlineplus.gov/druginfo/meds/a682727.html',
    'Drug Name: Ibuprofen, Link: https://medlineplus.gov/druginfo/meds/a682159.html',
    'Drug Name: Pseudoephedrine, Link: https://medlineplus.gov/druginfo/meds/a682619.html',
    'Drug Name: Pseudoephedrine, Link: https://medlineplus.gov/druginfo/meds/a682619.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Ibuprofen, Link: https://medlineplus.gov/druginfo/meds/a682159.html',
    'Drug Name: Diphenhydramine, Link: https://medlineplus.gov/druginfo/meds/a682539.html',
    'Drug Name: Amphetamine, Link: https://medlineplus.gov/druginfo/meds/a616004.html',
    'Drug Name: Amphetamine, Link: https://medlineplus.gov/druginfo/meds/a616004.html',
    'Drug Name: Rifamycin, Link: https://medlineplus.gov/druginfo/meds/a619010.html',
    'Drug Name: Flunisolide Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a681048.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Theophylline, Link: https://medlineplus.gov/druginfo/meds/a681006.html',
    'Drug Name: Flunisolide Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a681048.html',
    'Drug Name: Afamitresgene Autoleucel Injection, Link: https://medlineplus.gov/druginfo/meds/a624042.html',
    'Drug Name: Afatinib, Link: https://medlineplus.gov/druginfo/meds/a613044.html',
    'Drug Name: Nifedipine, Link: https://medlineplus.gov/druginfo/meds/a684028.html',
    'Drug Name: Everolimus, Link: https://medlineplus.gov/druginfo/meds/a609032.html',
    'Drug Name: Everolimus, Link: https://medlineplus.gov/druginfo/meds/a609032.html',
    'Drug Name: Aflibercept Injection, Link: https://medlineplus.gov/druginfo/meds/a612004.html',
    'Drug Name: Influenza Vaccine, Inactivated or Recombinant, Link: https://medlineplus.gov/druginfo/meds/a607017.html',
    'Drug Name: Insulin Human Inhalation, Link: https://medlineplus.gov/druginfo/meds/a615014.html',
    'Drug Name: Oxymetazoline Nasal Spray, Link: https://medlineplus.gov/druginfo/meds/a608026.html',
    'Drug Name: Pseudoephedrine, Link: https://medlineplus.gov/druginfo/meds/a682619.html',
    'Drug Name: Tolnaftate, Link: https://medlineplus.gov/druginfo/meds/a682617.html',
    'Drug Name: Tolnaftate, Link: https://medlineplus.gov/druginfo/meds/a682617.html',
    'Drug Name: Tolnaftate, Link: https://medlineplus.gov/druginfo/meds/a682617.html',
    'Drug Name: Diphenhydramine Topical, Link: https://medlineplus.gov/druginfo/meds/a601044.html',
    'Drug Name: Agalsidase beta Injection, Link: https://medlineplus.gov/druginfo/meds/a623025.html',
    'Drug Name: Vamorolone, Link: https://medlineplus.gov/druginfo/meds/a624005.html',
    'Drug Name: Aspirin and Extended-Release Dipyridamole, Link: https://medlineplus.gov/druginfo/meds/a699053.html',
    'Drug Name: Loratadine, Link: https://medlineplus.gov/druginfo/meds/a697038.html',
    'Drug Name: Anagrelide, Link: https://medlineplus.gov/druginfo/meds/a601020.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Chlorpheniramine, Link: https://medlineplus.gov/druginfo/meds/a682543.html',
    'Drug Name: AHFS® Patient Medication Information, Link: https://medlineplus.gov/druginfo/meds/index.html',
    'Drug Name: Pamidronate Injection, Link: https://medlineplus.gov/druginfo/meds/a601163.html',
    'Drug Name: Fluoride, Link: https://medlineplus.gov/druginfo/meds/a682727.html',
    'Drug Name: Erenumab-aooe Injection, Link: https://medlineplus.gov/druginfo/meds/a618029.html',
    'Drug Name: Guaifenesin, Link: https://medlineplus.gov/druginfo/meds/a682494.html',
    'Drug Name: Fluticasone and Salmeterol Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a699063.html',
    'Drug Name: Budesonide and Albuterol Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a623009.html',
    'Drug Name: Fremanezumab-vfrm Injection, Link: https://medlineplus.gov/druginfo/meds/a618053.html',
    'Drug Name: Prednisolone Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a682794.html',
    'Drug Name: Sulfacetamide Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a601114.html',
    'Drug Name: Tobramycin Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a682660.html',
    'Drug Name: Levobunolol Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a686011.html',
    'Drug Name: Niraparib and Abiraterone, Link: https://medlineplus.gov/druginfo/meds/a623037.html',
    'Drug Name: Trifarotene Topical, Link: https://medlineplus.gov/druginfo/meds/a620004.html',
    'Drug Name: Cyclopentolate Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a616014.html',
    'Drug Name: Dipivefrin Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a686005.html',
    'Drug Name: Salicylic Acid Topical, Link: https://medlineplus.gov/druginfo/meds/a607072.html',
    'Drug Name: Salicylic Acid Topical, Link: https://medlineplus.gov/druginfo/meds/a607072.html',
    'Drug Name: Netupitant and Palonosetron, Link: https://medlineplus.gov/druginfo/meds/a614053.html',
    'Drug Name: Hydrocortisone Topical, Link: https://medlineplus.gov/druginfo/meds/a682793.html',
    'Drug Name: Brompheniramine, Link: https://medlineplus.gov/druginfo/meds/a682545.html',
    'Drug Name: Brompheniramine, Link: https://medlineplus.gov/druginfo/meds/a682545.html',
    'Drug Name: Brompheniramine, Link: https://medlineplus.gov/druginfo/meds/a682545.html',
    'Drug Name: Hydrocortisone Topical, Link: https://medlineplus.gov/druginfo/meds/a682793.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Diphenhydramine, Link: https://medlineplus.gov/druginfo/meds/a682539.html',
    'Drug Name: Aluminum Hydroxide and Magnesium Hydroxide, Link: https://medlineplus.gov/druginfo/meds/a601013.html',
    'Drug Name: Simethicone, Link: https://medlineplus.gov/druginfo/meds/a682683.html',
    'Drug Name: Loratadine, Link: https://medlineplus.gov/druginfo/meds/a697038.html',
    'Drug Name: Pseudoephedrine, Link: https://medlineplus.gov/druginfo/meds/a682619.html',
    'Drug Name: Loratadine, Link: https://medlineplus.gov/druginfo/meds/a697038.html',
    'Drug Name: Ketotifen Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a604033.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Albendazole, Link: https://medlineplus.gov/druginfo/meds/a610019.html',
    'Drug Name: Albendazole, Link: https://medlineplus.gov/druginfo/meds/a610019.html',
    'Drug Name: Albiglutide Injection, Link: https://medlineplus.gov/druginfo/meds/a614031.html',
    'Drug Name: Albuterol, Link: https://medlineplus.gov/druginfo/meds/a607004.html',
    'Drug Name: Albuterol and Ipratropium Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a601063.html',
    'Drug Name: Albuterol Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a682145.html',
    'Drug Name: Alcaftadine Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a611022.html',
    'Drug Name: Spironolactone and Hydrochlorothiazide, Link: https://medlineplus.gov/druginfo/meds/a601111.html',
    'Drug Name: Spironolactone, Link: https://medlineplus.gov/druginfo/meds/a682627.html',
    'Drug Name: Imiquimod Topical, Link: https://medlineplus.gov/druginfo/meds/a698010.html',
    'Drug Name: Aldesleukin, Link: https://medlineplus.gov/druginfo/meds/a692009.html',
    'Drug Name: Guaifenesin, Link: https://medlineplus.gov/druginfo/meds/a682494.html',
    'Drug Name: Doxylamine, Link: https://medlineplus.gov/druginfo/meds/a682537.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Diphenhydramine, Link: https://medlineplus.gov/druginfo/meds/a682539.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Pseudoephedrine, Link: https://medlineplus.gov/druginfo/meds/a682619.html',
    'Drug Name: Pseudoephedrine, Link: https://medlineplus.gov/druginfo/meds/a682619.html',
    'Drug Name: Methyldopa, Link: https://medlineplus.gov/druginfo/meds/a682242.html',
    'Drug Name: Chlorothiazide, Link: https://medlineplus.gov/druginfo/meds/a682341.html',
    'Drug Name: Methyldopa, Link: https://medlineplus.gov/druginfo/meds/a682242.html',
    'Drug Name: Methyldopa and Hydrochlorothiazide, Link: https://medlineplus.gov/druginfo/meds/a601076.html',
    'Drug Name: Simethicone, Link: https://medlineplus.gov/druginfo/meds/a682683.html',
    'Drug Name: Alectinib, Link: https://medlineplus.gov/druginfo/meds/a616007.html',
    'Drug Name: Alectinib, Link: https://medlineplus.gov/druginfo/meds/a616007.html',
    'Drug Name: Alemtuzumab Injection (Chronic Lymphocytic Leukemia), Link: https://medlineplus.gov/druginfo/meds/a608053.html',
    'Drug Name: Alemtuzumab Injection (Multiple Sclerosis), Link: https://medlineplus.gov/druginfo/meds/a619012.html',
    'Drug Name: Alendronate, Link: https://medlineplus.gov/druginfo/meds/a601011.html',
    'Drug Name: Diphenhydramine, Link: https://medlineplus.gov/druginfo/meds/a682539.html',
    'Drug Name: Naproxen, Link: https://medlineplus.gov/druginfo/meds/a681029.html',
    'Drug Name: Naproxen, Link: https://medlineplus.gov/druginfo/meds/a681029.html',
    'Drug Name: Diphenhydramine, Link: https://medlineplus.gov/druginfo/meds/a682539.html',
    'Drug Name: Pseudoephedrine, Link: https://medlineplus.gov/druginfo/meds/a682619.html',
    'Drug Name: Alfuzosin, Link: https://medlineplus.gov/druginfo/meds/a604002.html',
    'Drug Name: Pemetrexed Injection, Link: https://medlineplus.gov/druginfo/meds/a607043.html',
    'Drug Name: Nitazoxanide, Link: https://medlineplus.gov/druginfo/meds/a603017.html',
    'Drug Name: Copanlisib Injection, Link: https://medlineplus.gov/druginfo/meds/a617044.html',
    'Drug Name: Alirocumab Injection, Link: https://medlineplus.gov/druginfo/meds/a615035.html',
    'Drug Name: Aliskiren, Link: https://medlineplus.gov/druginfo/meds/a607039.html',
    'Drug Name: Alitretinoin, Link: https://medlineplus.gov/druginfo/meds/a601012.html',
    'Drug Name: Calcium Carbonate, Link: https://medlineplus.gov/druginfo/meds/a601032.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Simethicone, Link: https://medlineplus.gov/druginfo/meds/a682683.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Sodium Bicarbonate, Link: https://medlineplus.gov/druginfo/meds/a682001.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Dextromethorphan, Link: https://medlineplus.gov/druginfo/meds/a682492.html',
    'Drug Name: Chlorpheniramine, Link: https://medlineplus.gov/druginfo/meds/a682543.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Dextromethorphan, Link: https://medlineplus.gov/druginfo/meds/a682492.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Dextromethorphan, Link: https://medlineplus.gov/druginfo/meds/a682492.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Dextromethorphan, Link: https://medlineplus.gov/druginfo/meds/a682492.html',
    'Drug Name: Dextromethorphan, Link: https://medlineplus.gov/druginfo/meds/a682492.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Dextromethorphan, Link: https://medlineplus.gov/druginfo/meds/a682492.html',
    'Drug Name: Doxylamine, Link: https://medlineplus.gov/druginfo/meds/a682537.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Melphalan Injection, Link: https://medlineplus.gov/druginfo/meds/a612019.html',
    'Drug Name: Melphalan, Link: https://medlineplus.gov/druginfo/meds/a682220.html',
    'Drug Name: Ergoloid Mesylates, Link: https://medlineplus.gov/druginfo/meds/a682097.html',
    'Drug Name: Hydrocortisone, Link: https://medlineplus.gov/druginfo/meds/a682206.html',
    'Drug Name: Hydrocodone Combination Products, Link: https://medlineplus.gov/druginfo/meds/a601006.html',
    'Drug Name: Fexofenadine, Link: https://medlineplus.gov/druginfo/meds/a697035.html',
    'Drug Name: Fexofenadine and Pseudoephedrine, Link: https://medlineplus.gov/druginfo/meds/a601053.html',
    'Drug Name: Pseudoephedrine, Link: https://medlineplus.gov/druginfo/meds/a682619.html',
    'Drug Name: Chlorpheniramine, Link: https://medlineplus.gov/druginfo/meds/a682543.html',
    'Drug Name: Chlorpheniramine, Link: https://medlineplus.gov/druginfo/meds/a682543.html',
    'Drug Name: Cetirizine, Link: https://medlineplus.gov/druginfo/meds/a623043.html',
    'Drug Name: Cetirizine, Link: https://medlineplus.gov/druginfo/meds/a623043.html',
    'Drug Name: Chlorpheniramine, Link: https://medlineplus.gov/druginfo/meds/a682543.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Diphenhydramine, Link: https://medlineplus.gov/druginfo/meds/a682539.html',
    'Drug Name: Diphenhydramine Topical, Link: https://medlineplus.gov/druginfo/meds/a601044.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Pseudoephedrine, Link: https://medlineplus.gov/druginfo/meds/a682619.html',
    'Drug Name: Diphenhydramine, Link: https://medlineplus.gov/druginfo/meds/a682539.html',
    'Drug Name: Triamcinolone Nasal Spray, Link: https://medlineplus.gov/druginfo/meds/a682791.html',
    'Drug Name: Cetirizine, Link: https://medlineplus.gov/druginfo/meds/a623043.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Orlistat, Link: https://medlineplus.gov/druginfo/meds/a601244.html',
    'Drug Name: Allopurinol, Link: https://medlineplus.gov/druginfo/meds/a682673.html',
    'Drug Name: Allopurinol Injection, Link: https://medlineplus.gov/druginfo/meds/a622045.html',
    'Drug Name: Naloxone Injection, Link: https://medlineplus.gov/druginfo/meds/a612022.html',
    'Drug Name: Simethicone, Link: https://medlineplus.gov/druginfo/meds/a682683.html',
    'Drug Name: Magnesium Hydroxide, Link: https://medlineplus.gov/druginfo/meds/a601073.html',
    'Drug Name: Magnesium Gluconate, Link: https://medlineplus.gov/druginfo/meds/a601072.html',
    'Drug Name: Almotriptan, Link: https://medlineplus.gov/druginfo/meds/a603028.html',
    'Drug Name: Nedocromil Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a601243.html',
    'Drug Name: Alogliptin, Link: https://medlineplus.gov/druginfo/meds/a613026.html',
    'Drug Name: Lodoxamide Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a694014.html',
    'Drug Name: Allopurinol Injection, Link: https://medlineplus.gov/druginfo/meds/a622045.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Estradiol Transdermal Patch, Link: https://medlineplus.gov/druginfo/meds/a605042.html',
    'Drug Name: Alosetron, Link: https://medlineplus.gov/druginfo/meds/a601230.html',
    'Drug Name: Palonosetron Injection, Link: https://medlineplus.gov/druginfo/meds/a610002.html',
    'Drug Name: Alpelisib, Link: https://medlineplus.gov/druginfo/meds/a619036.html',
    'Drug Name: Vitamin E (Alpha-Tocopherol), Link: https://medlineplus.gov/druginfo/meds/a621029.html',
    'Drug Name: Brimonidine Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a601232.html',
    'Drug Name: Betamethasone Topical, Link: https://medlineplus.gov/druginfo/meds/a682799.html',
    'Drug Name: Alprazolam, Link: https://medlineplus.gov/druginfo/meds/a684001.html',
    'Drug Name: Alprostadil Urogenital, Link: https://medlineplus.gov/druginfo/meds/a695022.html',
    'Drug Name: Psyllium, Link: https://medlineplus.gov/druginfo/meds/a601104.html',
    'Drug Name: Loteprednol Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a619025.html',
    'Drug Name: Sumatriptan Injection, Link: https://medlineplus.gov/druginfo/meds/a696023.html',
    'Drug Name: Retapamulin, Link: https://medlineplus.gov/druginfo/meds/a607049.html',
    'Drug Name: Ramipril, Link: https://medlineplus.gov/druginfo/meds/a692027.html',
    'Drug Name: Diphenhydramine, Link: https://medlineplus.gov/druginfo/meds/a682539.html',
    'Drug Name: Aluminum Hydroxide, Link: https://medlineplus.gov/druginfo/meds/a699048.html',
    'Drug Name: Tretinoin Topical, Link: https://medlineplus.gov/druginfo/meds/a682437.html',
    'Drug Name: Lovastatin, Link: https://medlineplus.gov/druginfo/meds/a688006.html',
    'Drug Name: Lovastatin, Link: https://medlineplus.gov/druginfo/meds/a688006.html',
    'Drug Name: Tretinoin Topical, Link: https://medlineplus.gov/druginfo/meds/a682437.html',
    'Drug Name: Altretamine, Link: https://medlineplus.gov/druginfo/meds/a601200.html',
    'Drug Name: Aluminum Hydroxide, Link: https://medlineplus.gov/druginfo/meds/a699048.html',
    'Drug Name: Aluminum Hydroxide, Link: https://medlineplus.gov/druginfo/meds/a699048.html',
    'Drug Name: Aluminum Hydroxide and Magnesium Hydroxide, Link: https://medlineplus.gov/druginfo/meds/a601013.html',
    'Drug Name: Aluminum Hydroxide, Link: https://medlineplus.gov/druginfo/meds/a699048.html',
    'Drug Name: Aluminum Hydroxide and Magnesium Hydroxide, Link: https://medlineplus.gov/druginfo/meds/a601013.html',
    'Drug Name: Magnesium Hydroxide, Link: https://medlineplus.gov/druginfo/meds/a601073.html',
    'Drug Name: Brigatinib, Link: https://medlineplus.gov/druginfo/meds/a617016.html',
    'Drug Name: Metaproterenol, Link: https://medlineplus.gov/druginfo/meds/a682084.html',
    'Drug Name: Ciclesonide Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a609004.html',
    'Drug Name: Alvimopan, Link: https://medlineplus.gov/druginfo/meds/a608051.html',
    'Drug Name: Bevacizumab Injection, Link: https://medlineplus.gov/druginfo/meds/a607001.html',
    'Drug Name: Amantadine, Link: https://medlineplus.gov/druginfo/meds/a682064.html',
    'Drug Name: Glimepiride, Link: https://medlineplus.gov/druginfo/meds/a696016.html',
    'Drug Name: Codeine, Link: https://medlineplus.gov/druginfo/meds/a682065.html',
    'Drug Name: Zolpidem, Link: https://medlineplus.gov/druginfo/meds/a693025.html',
    'Drug Name: Zolpidem, Link: https://medlineplus.gov/druginfo/meds/a693025.html',
    'Drug Name: Pseudoephedrine, Link: https://medlineplus.gov/druginfo/meds/a682619.html',
    'Drug Name: Pseudoephedrine, Link: https://medlineplus.gov/druginfo/meds/a682619.html',
    'Drug Name: Amphotericin B Liposomal Injection, Link: https://medlineplus.gov/druginfo/meds/a616018.html',
    'Drug Name: Ambrisentan, Link: https://medlineplus.gov/druginfo/meds/a612023.html',
    'Drug Name: Ampicillin, Link: https://medlineplus.gov/druginfo/meds/a685002.html',
    'Drug Name: Medroxyprogesterone, Link: https://medlineplus.gov/druginfo/meds/a682470.html',
    'Drug Name: Fluoride, Link: https://medlineplus.gov/druginfo/meds/a682727.html',
    'Drug Name: Naratriptan, Link: https://medlineplus.gov/druginfo/meds/a601083.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Methotrexate Injection, Link: https://medlineplus.gov/druginfo/meds/a682018.html',
    'Drug Name: Methotrexate, Link: https://medlineplus.gov/druginfo/meds/a682019.html',
    'Drug Name: Aminocaproic Acid Injection, Link: https://medlineplus.gov/druginfo/meds/a608024.html',
    'Drug Name: Aminocaproic Acid, Link: https://medlineplus.gov/druginfo/meds/a608023.html',
    'Drug Name: Aminocaproic Acid, Link: https://medlineplus.gov/druginfo/meds/a608023.html',
    'Drug Name: Amifostine Injection, Link: https://medlineplus.gov/druginfo/meds/a696014.html',
    'Drug Name: Amikacin Injection, Link: https://medlineplus.gov/druginfo/meds/a682661.html',
    'Drug Name: Amikacin Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a623020.html',
    'Drug Name: Amikacin Injection, Link: https://medlineplus.gov/druginfo/meds/a682661.html',
    'Drug Name: Amiloride, Link: https://medlineplus.gov/druginfo/meds/a615029.html',
    'Drug Name: Amiloride and Hydrochlorothiazide, Link: https://medlineplus.gov/druginfo/meds/a601014.html',
    'Drug Name: Ampicillin Injection, Link: https://medlineplus.gov/druginfo/meds/a601133.html',
    'Drug Name: Ampicillin, Link: https://medlineplus.gov/druginfo/meds/a685002.html',
    'Drug Name: Aminocaproic Acid, Link: https://medlineplus.gov/druginfo/meds/a608023.html',
    'Drug Name: Aminocaproic Acid Injection, Link: https://medlineplus.gov/druginfo/meds/a608024.html',
    'Drug Name: Aminolevulinic Acid Topical, Link: https://medlineplus.gov/druginfo/meds/a607062.html',
    'Drug Name: Aminophylline, Link: https://medlineplus.gov/druginfo/meds/a601015.html',
    'Drug Name: Aminophylline, Link: https://medlineplus.gov/druginfo/meds/a601015.html',
    'Drug Name: Amiodarone, Link: https://medlineplus.gov/druginfo/meds/a687009.html',
    'Drug Name: Amisulpride Injection, Link: https://medlineplus.gov/druginfo/meds/a622062.html',
    'Drug Name: Amitriptyline, Link: https://medlineplus.gov/druginfo/meds/a682388.html',
    'Drug Name: Lubiprostone, Link: https://medlineplus.gov/druginfo/meds/a607034.html',
    'Drug Name: Amitriptyline, Link: https://medlineplus.gov/druginfo/meds/a682388.html',
    'Drug Name: Amitriptyline, Link: https://medlineplus.gov/druginfo/meds/a682388.html',
    'Drug Name: Amivantamab-vmjw Injection, Link: https://medlineplus.gov/druginfo/meds/a621034.html',
    'Drug Name: Adalimumab Injection, Link: https://medlineplus.gov/druginfo/meds/a603010.html',
    'Drug Name: Amlexanox, Link: https://medlineplus.gov/druginfo/meds/a601017.html',
    'Drug Name: Amlodipine and Benazepril, Link: https://medlineplus.gov/druginfo/meds/a601018.html',
    'Drug Name: Amlodipine, Link: https://medlineplus.gov/druginfo/meds/a692044.html',
    'Drug Name: Amlodipine and Benazepril, Link: https://medlineplus.gov/druginfo/meds/a601018.html',
    'Drug Name: Ammonium Lactate Topical, Link: https://medlineplus.gov/druginfo/meds/a617028.html',
    'Drug Name: Isotretinoin, Link: https://medlineplus.gov/druginfo/meds/a681043.html',
    'Drug Name: Estrogen, Link: https://medlineplus.gov/druginfo/meds/a682922.html',
    'Drug Name: Meprobamate, Link: https://medlineplus.gov/druginfo/meds/a682077.html',
    'Drug Name: Amoxapine, Link: https://medlineplus.gov/druginfo/meds/a682202.html',
    'Drug Name: Amoxicillin, Link: https://medlineplus.gov/druginfo/meds/a685001.html',
    'Drug Name: Amoxicillin and Clavulanic Acid, Link: https://medlineplus.gov/druginfo/meds/a685024.html',
    'Drug Name: Amoxicillin, Link: https://medlineplus.gov/druginfo/meds/a685001.html',
    'Drug Name: Amphetamine, Link: https://medlineplus.gov/druginfo/meds/a616004.html',
    'Drug Name: Aluminum Hydroxide, Link: https://medlineplus.gov/druginfo/meds/a699048.html',
    'Drug Name: Amphotericin B Lipid Complex Injection, Link: https://medlineplus.gov/druginfo/meds/a601132.html',
    'Drug Name: Amphotericin B Injection, Link: https://medlineplus.gov/druginfo/meds/a682643.html',
    'Drug Name: Amphotericin B Lipid Complex Injection, Link: https://medlineplus.gov/druginfo/meds/a601132.html',
    'Drug Name: Amphotericin B Liposomal Injection, Link: https://medlineplus.gov/druginfo/meds/a616018.html',
    'Drug Name: Ampicillin, Link: https://medlineplus.gov/druginfo/meds/a685002.html',
    'Drug Name: Ampicillin and Sulbactam Injection, Link: https://medlineplus.gov/druginfo/meds/a693021.html',
    'Drug Name: Ampicillin Injection, Link: https://medlineplus.gov/druginfo/meds/a601133.html',
    'Drug Name: Dalfampridine, Link: https://medlineplus.gov/druginfo/meds/a611005.html',
    'Drug Name: Cyclobenzaprine, Link: https://medlineplus.gov/druginfo/meds/a682514.html',
    'Drug Name: Lifileucel Injection, Link: https://medlineplus.gov/druginfo/meds/a624019.html',
    'Drug Name: Amlodipine, Link: https://medlineplus.gov/druginfo/meds/a692044.html',
    'Drug Name: Vutrisiran Injection, Link: https://medlineplus.gov/druginfo/meds/a622061.html',
    'Drug Name: Minocycline Topical, Link: https://medlineplus.gov/druginfo/meds/a620003.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Diphenhydramine, Link: https://medlineplus.gov/druginfo/meds/a682539.html',
    'Drug Name: Clomipramine, Link: https://medlineplus.gov/druginfo/meds/a697002.html',
    'Drug Name: Anagrelide, Link: https://medlineplus.gov/druginfo/meds/a601020.html',
    'Drug Name: Anakinra, Link: https://medlineplus.gov/druginfo/meds/a602001.html',
    'Drug Name: Naproxen, Link: https://medlineplus.gov/druginfo/meds/a681029.html',
    'Drug Name: Naproxen, Link: https://medlineplus.gov/druginfo/meds/a681029.html',
    'Drug Name: Anastrozole, Link: https://medlineplus.gov/druginfo/meds/a696018.html',
    'Drug Name: Barium Sulfate, Link: https://medlineplus.gov/druginfo/meds/a606010.html',
    'Drug Name: Cefazolin Injection, Link: https://medlineplus.gov/druginfo/meds/a682731.html',
    'Drug Name: Testosterone Transdermal Patch, Link: https://medlineplus.gov/druginfo/meds/a601118.html',
    'Drug Name: Testosterone Topical, Link: https://medlineplus.gov/druginfo/meds/a605020.html',
    'Drug Name: Fluoxymesterone, Link: https://medlineplus.gov/druginfo/meds/a682690.html',
    'Drug Name: Fluoxymesterone, Link: https://medlineplus.gov/druginfo/meds/a682690.html',
    'Drug Name: Oxymetazoline Nasal Spray, Link: https://medlineplus.gov/druginfo/meds/a608026.html',
    'Drug Name: Hydrocodone Combination Products, Link: https://medlineplus.gov/druginfo/meds/a601006.html',
    'Drug Name: Estrogen and Progestin (Hormone Replacement Therapy), Link: https://medlineplus.gov/druginfo/meds/a601041.html',
    'Drug Name: Anifrolumab-fnia Injection, Link: https://medlineplus.gov/druginfo/meds/a621046.html',
    'Drug Name: Meloxicam Injection, Link: https://medlineplus.gov/druginfo/meds/a620024.html',
    'Drug Name: Nogapendekin alfa inbakicept-pmln Intravesical, Link: https://medlineplus.gov/druginfo/meds/a624034.html',
    'Drug Name: Estrogen and Progestin (Vaginal Ring Contraceptives), Link: https://medlineplus.gov/druginfo/meds/a604032.html',
    'Drug Name: Acetaminophen, Butalbital, and Caffeine, Link: https://medlineplus.gov/druginfo/meds/a601009.html',
    'Drug Name: Umeclidinium and Vilanterol Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a614019.html',
    'Drug Name: Flurbiprofen, Link: https://medlineplus.gov/druginfo/meds/a687005.html',
    'Drug Name: Disulfiram, Link: https://medlineplus.gov/druginfo/meds/a682602.html',
    'Drug Name: Aluminum Hydroxide and Magnesium Hydroxide, Link: https://medlineplus.gov/druginfo/meds/a601013.html',
    'Drug Name: Aluminum Hydroxide and Magnesium Hydroxide, Link: https://medlineplus.gov/druginfo/meds/a601013.html',
    'Drug Name: Aluminum Hydroxide and Magnesium Hydroxide, Link: https://medlineplus.gov/druginfo/meds/a601013.html',
    'Drug Name: Fenofibrate, Link: https://medlineplus.gov/druginfo/meds/a601052.html',
    'Drug Name: Anthrax Vaccine, Link: https://medlineplus.gov/druginfo/meds/a607013.html',
    'Drug Name: Diphenhydramine Topical, Link: https://medlineplus.gov/druginfo/meds/a601044.html',
    'Drug Name: Diphenhydramine Topical, Link: https://medlineplus.gov/druginfo/meds/a601044.html',
    'Drug Name: Infliximab Injection, Link: https://medlineplus.gov/druginfo/meds/a604023.html',
    'Drug Name: Infliximab Injection, Link: https://medlineplus.gov/druginfo/meds/a604023.html',
    'Drug Name: Antipyrine-Benzocaine Otic, Link: https://medlineplus.gov/druginfo/meds/a607073.html',
    'Drug Name: Meclizine, Link: https://medlineplus.gov/druginfo/meds/a682548.html',
    'Drug Name: Sulfinpyrazone, Link: https://medlineplus.gov/druginfo/meds/a682339.html',
    'Drug Name: Hydrocortisone Rectal, Link: https://medlineplus.gov/druginfo/meds/a617001.html',
    'Drug Name: Hydrocortisone Topical, Link: https://medlineplus.gov/druginfo/meds/a682793.html',
    'Drug Name: Dolasetron, Link: https://medlineplus.gov/druginfo/meds/a601001.html',
    'Drug Name: Dolasetron Injection, Link: https://medlineplus.gov/druginfo/meds/a601214.html',
    'Drug Name: Benzhydrocodone and Acetaminophen, Link: https://medlineplus.gov/druginfo/meds/a620007.html',
    'Drug Name: Apalutamide, Link: https://medlineplus.gov/druginfo/meds/a618018.html',
    'Drug Name: Acetaminophen Injection, Link: https://medlineplus.gov/druginfo/meds/a611019.html',
    'Drug Name: Acetaminophen, Link: https://medlineplus.gov/druginfo/meds/a681004.html',
    'Drug Name: Acetaminophen and Codeine, Link: https://medlineplus.gov/druginfo/meds/a601005.html',
    'Drug Name: Amlexanox, Link: https://medlineplus.gov/druginfo/meds/a601017.html',
    'Drug Name: Insulin Glulisine (rDNA origin) Injection, Link: https://medlineplus.gov/druginfo/meds/a607033.html',
    'Drug Name: Apixaban, Link: https://medlineplus.gov/druginfo/meds/a613032.html',
    'Drug Name: Bupropion, Link: https://medlineplus.gov/druginfo/meds/a695033.html',
    'Drug Name: Apomorphine Injection, Link: https://medlineplus.gov/druginfo/meds/a604020.html',
    'Drug Name: Apomorphine Injection, Link: https://medlineplus.gov/druginfo/meds/a604020.html',
    'Drug Name: Apomorphine Sublingual, Link: https://medlineplus.gov/druginfo/meds/a620044.html',
    'Drug Name: Penicillin G Procaine Injection, Link: https://medlineplus.gov/druginfo/meds/a615052.html',
    'Drug Name: Apraclonidine Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a608005.html',
    'Drug Name: Apremilast, Link: https://medlineplus.gov/druginfo/meds/a614022.html',
    'Drug Name: Aprepitant, Link: https://medlineplus.gov/druginfo/meds/a604003.html',
    'Drug Name: Aprepitant/Fosaprepitant Injection, Link: https://medlineplus.gov/druginfo/meds/a617042.html',
    'Drug Name: Hydralazine, Link: https://medlineplus.gov/druginfo/meds/a682246.html',
    'Drug Name: Hydrochlorothiazide, Link: https://medlineplus.gov/druginfo/meds/a682571.html',
    'Drug Name: Hydralazine, Link: https://medlineplus.gov/druginfo/meds/a682246.html',
    'Drug Name: Hydralazine, Link: https://medlineplus.gov/druginfo/meds/a682246.html',
    'Drug Name: Cabotegravir injection, Link: https://medlineplus.gov/druginfo/meds/a622053.html',
    'Drug Name: Estrogen and Progestin (Oral Contraceptives), Link: https://medlineplus.gov/druginfo/meds/a601050.html',
    'Drug Name: Mesalamine, Link: https://medlineplus.gov/druginfo/meds/a688021.html',
    'Drug Name: Aprocitentan, Link: https://medlineplus.gov/druginfo/meds/a624023.html',
    'Drug Name: Methylphenidate, Link: https://medlineplus.gov/druginfo/meds/a682188.html',
    'Drug Name: Eslicarbazepine, Link: https://medlineplus.gov/druginfo/meds/a614032.html',
    'Drug Name: Tipranavir, Link: https://medlineplus.gov/druginfo/meds/a606009.html',
    'Drug Name: Chloral Hydrate, Link: https://medlineplus.gov/druginfo/meds/a682201.html',
    'Drug Name: Fluoride, Link: https://medlineplus.gov/druginfo/meds/a682727.html',
    'Drug Name: Theophylline, Link: https://medlineplus.gov/druginfo/meds/a681006.html',
    'Drug Name: Vitamin A, Link: https://medlineplus.gov/druginfo/meds/a621028.html',
    'Drug Name: Vitamin E (Alpha-Tocopherol), Link: https://medlineplus.gov/druginfo/meds/a621029.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Methyclothiazide, Link: https://medlineplus.gov/druginfo/meds/a682569.html',
    'Drug Name: Cytarabine, Link: https://medlineplus.gov/druginfo/meds/a682222.html',
    'Drug Name: Cytarabine, Link: https://medlineplus.gov/druginfo/meds/a682222.html',
    'Drug Name: Tafenoquine, Link: https://medlineplus.gov/druginfo/meds/a618050.html',
    'Drug Name: Chloroquine, Link: https://medlineplus.gov/druginfo/meds/a682318.html',
    'Drug Name: Estrogen and Progestin (Oral Contraceptives), Link: https://medlineplus.gov/druginfo/meds/a601050.html',
    'Drug Name: Darbepoetin Alfa Injection, Link: https://medlineplus.gov/druginfo/meds/a604022.html',
    'Drug Name: Leflunomide, Link: https://medlineplus.gov/druginfo/meds/a600032.html',
    'Drug Name: Rilonacept Injection, Link: https://medlineplus.gov/druginfo/meds/a622030.html',
    'Drug Name: Indacaterol Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a612014.html',
    'Drug Name: Pamidronate Injection, Link: https://medlineplus.gov/druginfo/meds/a601163.html',
    'Drug Name: RSV (Respiratory Syncytial Virus) Vaccine, Link: https://medlineplus.gov/druginfo/meds/a623035.html',
    'Drug Name: Arformoterol Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a607061.html',
    'Drug Name: Donepezil, Link: https://medlineplus.gov/druginfo/meds/a697032.html',
    'Drug Name: Donepezil, Link: https://medlineplus.gov/druginfo/meds/a697032.html',
    'Drug Name: Phenylephrine, Link: https://medlineplus.gov/druginfo/meds/a606008.html',
    'Drug Name: Amikacin Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a623020.html',
    'Drug Name: Anastrozole, Link: https://medlineplus.gov/druginfo/meds/a696018.html',
    'Drug Name: Aripiprazole, Link: https://medlineplus.gov/druginfo/meds/a603012.html',
    'Drug Name: Aripiprazole Injection, Link: https://medlineplus.gov/druginfo/meds/a615048.html',
    'Drug Name: Aripiprazole Injection, Link: https://medlineplus.gov/druginfo/meds/a615048.html',
    'Drug Name: Aripiprazole Injection, Link: https://medlineplus.gov/druginfo/meds/a615048.html',
    'Drug Name: Triamcinolone, Link: https://medlineplus.gov/druginfo/meds/a601122.html',
    'Drug Name: Triamcinolone Topical, Link: https://medlineplus.gov/druginfo/meds/a601124.html',
    'Drug Name: Triamcinolone Topical, Link: https://medlineplus.gov/druginfo/meds/a601124.html',
    'Drug Name: Triamcinolone Topical, Link: https://medlineplus.gov/druginfo/meds/a601124.html',
    'Drug Name: Fondaparinux Injection, Link: https://medlineplus.gov/druginfo/meds/a612026.html',
    'Drug Name: Armodafinil, Link: https://medlineplus.gov/druginfo/meds/a607067.html',
    'Drug Name: Fluticasone Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a601056.html',
    'Drug Name: Thyroid, Link: https://medlineplus.gov/druginfo/meds/a682475.html',
    'Drug Name: Fluticasone Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a601056.html',
    'Drug Name: Exemestane, Link: https://medlineplus.gov/druginfo/meds/a607006.html',
    'Drug Name: Nelarabine Injection, Link: https://medlineplus.gov/druginfo/meds/a607077.html',
    'Drug Name: Arsenic Trioxide Injection, Link: https://medlineplus.gov/druginfo/meds/a608017.html',
    'Drug Name: Trihexyphenidyl, Link: https://medlineplus.gov/druginfo/meds/a682160.html',
    'Drug Name: Artemether and Lumefantrine, Link: https://medlineplus.gov/druginfo/meds/a609024.html',
    'Drug Name: Diclofenac and Misoprostol, Link: https://medlineplus.gov/druginfo/meds/a699002.html',
    'Drug Name: Morphine, Link: https://medlineplus.gov/druginfo/meds/a682133.html',
    'Drug Name: Ofatumumab Injection (Chronic Lymphocytic Leukemia), Link: https://medlineplus.gov/druginfo/meds/a610009.html',
    'Drug Name: Aspirin Rectal, Link: https://medlineplus.gov/druginfo/meds/a621021.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Mesalamine, Link: https://medlineplus.gov/druginfo/meds/a688021.html',
    'Drug Name: Mesalamine, Link: https://medlineplus.gov/druginfo/meds/a688021.html',
    'Drug Name: Theophylline, Link: https://medlineplus.gov/druginfo/meds/a681006.html',
    'Drug Name: Pyrantel, Link: https://medlineplus.gov/druginfo/meds/a682820.html',
    'Drug Name: Asciminib, Link: https://medlineplus.gov/druginfo/meds/a621055.html',
    'Drug Name: Ascorbic Acid (Vitamin C), Link: https://medlineplus.gov/druginfo/meds/a682583.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Asenapine, Link: https://medlineplus.gov/druginfo/meds/a610015.html',
    'Drug Name: Asenapine Transdermal Patch, Link: https://medlineplus.gov/druginfo/meds/a620019.html',
    'Drug Name: Amoxapine, Link: https://medlineplus.gov/druginfo/meds/a682202.html',
    'Drug Name: Mometasone Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a608035.html',
    'Drug Name: Mometasone Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a608035.html',
    'Drug Name: Asparaginase Erwinia Chrysanthemi (recombinant)-rywn Injection, Link: https://medlineplus.gov/druginfo/meds/a621042.html',
    'Drug Name: Asparaginase Erwinia Chrysanthemi Injection, Link: https://medlineplus.gov/druginfo/meds/a612034.html',
    'Drug Name: Calaspargase pegol-mknl Injection, Link: https://medlineplus.gov/druginfo/meds/a619015.html',
    'Drug Name: Lidocaine Transdermal Patch, Link: https://medlineplus.gov/druginfo/meds/a603026.html',
    'Drug Name: Capsaicin Topical, Link: https://medlineplus.gov/druginfo/meds/a620055.html',
    'Drug Name: Capsaicin Transdermal Patch, Link: https://medlineplus.gov/druginfo/meds/a620056.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Aspirin Rectal, Link: https://medlineplus.gov/druginfo/meds/a621021.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Aspirin and Extended-Release Dipyridamole, Link: https://medlineplus.gov/druginfo/meds/a699053.html',
    'Drug Name: Aspirin and Omeprazole, Link: https://medlineplus.gov/druginfo/meds/a617014.html',
    'Drug Name: Aspirin Rectal, Link: https://medlineplus.gov/druginfo/meds/a621021.html',
    'Drug Name: Aspirin, Butalbital, and Caffeine, Link: https://medlineplus.gov/druginfo/meds/a601023.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Tacrolimus, Link: https://medlineplus.gov/druginfo/meds/a601117.html',
    'Drug Name: Azelastine Nasal Spray, Link: https://medlineplus.gov/druginfo/meds/a697014.html',
    'Drug Name: Azelastine Nasal Spray, Link: https://medlineplus.gov/druginfo/meds/a697014.html',
    'Drug Name: Morphine Injection, Link: https://medlineplus.gov/druginfo/meds/a601161.html',
    'Drug Name: Candesartan, Link: https://medlineplus.gov/druginfo/meds/a601033.html',
    'Drug Name: Candesartan, Link: https://medlineplus.gov/druginfo/meds/a601033.html',
    'Drug Name: Hydroxyzine, Link: https://medlineplus.gov/druginfo/meds/a682866.html',
    'Drug Name: Atazanavir, Link: https://medlineplus.gov/druginfo/meds/a603019.html',
    'Drug Name: Atazanavir and Cobicistat, Link: https://medlineplus.gov/druginfo/meds/a622001.html',
    'Drug Name: Risedronate, Link: https://medlineplus.gov/druginfo/meds/a601247.html',
    'Drug Name: Atenolol, Link: https://medlineplus.gov/druginfo/meds/a684031.html',
    'Drug Name: Atezolizumab Injection, Link: https://medlineplus.gov/druginfo/meds/a616035.html',
    'Drug Name: Atidarsagene Autotemcel Injection, Link: https://medlineplus.gov/druginfo/meds/a624024.html',
    'Drug Name: Lorazepam, Link: https://medlineplus.gov/druginfo/meds/a682053.html',
    'Drug Name: Atogepant, Link: https://medlineplus.gov/druginfo/meds/a621052.html',
    'Drug Name: Atomoxetine, Link: https://medlineplus.gov/druginfo/meds/a603013.html',
    'Drug Name: Atorvastatin, Link: https://medlineplus.gov/druginfo/meds/a600045.html',
    'Drug Name: Atorvastatin, Link: https://medlineplus.gov/druginfo/meds/a600045.html',
    'Drug Name: Atovaquone, Link: https://medlineplus.gov/druginfo/meds/a693003.html',
    'Drug Name: Atovaquone and Proguanil, Link: https://medlineplus.gov/druginfo/meds/a619023.html',
    'Drug Name: Tretinoin Topical, Link: https://medlineplus.gov/druginfo/meds/a682437.html',
    'Drug Name: Efavirenz, Emtricitabine, and Tenofovir, Link: https://medlineplus.gov/druginfo/meds/a616048.html',
    'Drug Name: Efavirenz, Link: https://medlineplus.gov/druginfo/meds/a699004.html',
    'Drug Name: Chlorpheniramine, Link: https://medlineplus.gov/druginfo/meds/a682543.html',
    'Drug Name: Atropine Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a682487.html',
    'Drug Name: Atropine Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a682487.html',
    'Drug Name: Atropine Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a682487.html',
    'Drug Name: Ipratropium Oral Inhalation, Link: https://medlineplus.gov/druginfo/meds/a695021.html',
    'Drug Name: Ipratropium Nasal Spray, Link: https://medlineplus.gov/druginfo/meds/a618013.html',
    'Drug Name: Atazanavir, Link: https://medlineplus.gov/druginfo/meds/a603019.html',
    'Drug Name: Teriflunomide, Link: https://medlineplus.gov/druginfo/meds/a613010.html',
    'Drug Name: Amoxicillin and Clavulanic Acid, Link: https://medlineplus.gov/druginfo/meds/a685024.html',
    'Drug Name: Amoxicillin and Clavulanic Acid, Link: https://medlineplus.gov/druginfo/meds/a685024.html',
    'Drug Name: Repotrectinib, Link: https://medlineplus.gov/druginfo/meds/a623063.html',
    'Drug Name: Antipyrine-Benzocaine Otic, Link: https://medlineplus.gov/druginfo/meds/a607073.html',
    'Drug Name: Auranofin, Link: https://medlineplus.gov/druginfo/meds/a685038.html',
    'Drug Name: Antipyrine-Benzocaine Otic, Link: https://medlineplus.gov/druginfo/meds/a607073.html',
    'Drug Name: Ferric Citrate, Link: https://medlineplus.gov/druginfo/meds/a622004.html',
    'Drug Name: Deutetrabenazine, Link: https://medlineplus.gov/druginfo/meds/a617022.html',
    'Drug Name: Deutetrabenazine, Link: https://medlineplus.gov/druginfo/meds/a617022.html',
    'Drug Name: Dextromethorphan and Bupropion, Link: https://medlineplus.gov/druginfo/meds/a622070.html',
    'Drug Name: Epinephrine Injection, Link: https://medlineplus.gov/druginfo/meds/a603002.html',
    'Drug Name: Acyclovir Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a619029.html',
    'Drug Name: Avacopan, Link: https://medlineplus.gov/druginfo/meds/a622023.html',
    'Drug Name: Tazarotene Topical, Link: https://medlineplus.gov/druginfo/meds/a616052.html',
    'Drug Name: Hydromorphone Rectal, Link: https://medlineplus.gov/druginfo/meds/a613035.html',
    'Drug Name: Irbesartan, Link: https://medlineplus.gov/druginfo/meds/a698009.html',
    'Drug Name: Avanafil, Link: https://medlineplus.gov/druginfo/meds/a614010.html',
    'Drug Name: Metformin, Link: https://medlineplus.gov/druginfo/meds/a696005.html',
    'Drug Name: Rosiglitazone, Link: https://medlineplus.gov/druginfo/meds/a699023.html',
    'Drug Name: Glimepiride, Link: https://medlineplus.gov/druginfo/meds/a696016.html',
    'Drug Name: Rosiglitazone, Link: https://medlineplus.gov/druginfo/meds/a699023.html',
    'Drug Name: Rosiglitazone, Link: https://medlineplus.gov/druginfo/meds/a699023.html',
    'Drug Name: Avapritinib, Link: https://medlineplus.gov/druginfo/meds/a620013.html',
    'Drug Name: Irbesartan, Link: https://medlineplus.gov/druginfo/meds/a698009.html',
    'Drug Name: Bevacizumab Injection, Link: https://medlineplus.gov/druginfo/meds/a607001.html',
    'Drug Name: Avatrombopag, Link: https://medlineplus.gov/druginfo/meds/a618032.html',
    'Drug Name: Testosterone Injection, Link: https://medlineplus.gov/druginfo/meds/a614041.html',
    'Drug Name: Moxifloxacin, Link: https://medlineplus.gov/druginfo/meds/a600002.html',
    'Drug Name: Moxifloxacin Injection, Link: https://medlineplus.gov/druginfo/meds/a608030.html',
    'Drug Name: Avelumab Injection, Link: https://medlineplus.gov/druginfo/meds/a617006.html',
    'Drug Name: Nortriptyline, Link: https://medlineplus.gov/druginfo/meds/a682620.html',
    'Drug Name: Estrogen and Progestin (Oral Contraceptives), Link: https://medlineplus.gov/druginfo/meds/a601050.html',
    'Drug Name: Morphine, Link: https://medlineplus.gov/druginfo/meds/a682133.html',
    'Drug Name: Tretinoin Topical, Link: https://medlineplus.gov/druginfo/meds/a682437.html',
    'Drug Name: Dutasteride, Link: https://medlineplus.gov/druginfo/meds/a603001.html',
    'Drug Name: Interferon Beta-1a Intramuscular Injection, Link: https://medlineplus.gov/druginfo/meds/a693040.html',
    'Drug Name: Infliximab Injection, Link: https://medlineplus.gov/druginfo/meds/a604023.html',
    'Drug Name: Ceftazidime and Avibactam Injection, Link: https://medlineplus.gov/druginfo/meds/a615018.html',
    'Drug Name: Bevacizumab Injection, Link: https://medlineplus.gov/druginfo/meds/a607001.html',
    'Drug Name: Axatilimab-csfr Injection, Link: https://medlineplus.gov/druginfo/meds/a624043.html',
    'Drug Name: Almotriptan, Link: https://medlineplus.gov/druginfo/meds/a603028.html',
    'Drug Name: Axicabtagene Ciloleucel Injection, Link: https://medlineplus.gov/druginfo/meds/a618003.html',
    'Drug Name: Nizatidine, Link: https://medlineplus.gov/druginfo/meds/a694030.html',
    'Drug Name: Nizatidine, Link: https://medlineplus.gov/druginfo/meds/a694030.html',
    'Drug Name: Testosterone Topical, Link: https://medlineplus.gov/druginfo/meds/a605020.html',
    'Drug Name: Axitinib, Link: https://medlineplus.gov/druginfo/meds/a612017.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Norethindrone, Link: https://medlineplus.gov/druginfo/meds/a604034.html',
    'Drug Name: Avapritinib, Link: https://medlineplus.gov/druginfo/meds/a620013.html',
    'Drug Name: Azacitidine, Link: https://medlineplus.gov/druginfo/meds/a620060.html',
    'Drug Name: Azacitidine Injection, Link: https://medlineplus.gov/druginfo/meds/a607068.html',
    'Drug Name: Aztreonam Injection, Link: https://medlineplus.gov/druginfo/meds/a687010.html',
    'Drug Name: Azathioprine, Link: https://medlineplus.gov/druginfo/meds/a682167.html',
    'Drug Name: Azathioprine, Link: https://medlineplus.gov/druginfo/meds/a682167.html',
    'Drug Name: Hydrocodone Combination Products, Link: https://medlineplus.gov/druginfo/meds/a601006.html',
    'Drug Name: Aspirin, Link: https://medlineplus.gov/druginfo/meds/a682878.html',
    'Drug Name: Azelaic Acid Topical, Link: https://medlineplus.gov/druginfo/meds/a603020.html',
    'Drug Name: Azelastine Nasal Spray, Link: https://medlineplus.gov/druginfo/meds/a697014.html',
    'Drug Name: Azelastine Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a603009.html',
    'Drug Name: Azelaic Acid Topical, Link: https://medlineplus.gov/druginfo/meds/a603020.html',
    'Drug Name: Rasagiline, Link: https://medlineplus.gov/druginfo/meds/a606017.html',
    'Drug Name: Azilsartan, Link: https://medlineplus.gov/druginfo/meds/a611028.html',
    'Drug Name: Azithromycin, Link: https://medlineplus.gov/druginfo/meds/a697037.html',
    'Drug Name: Phenazopyridine, Link: https://medlineplus.gov/druginfo/meds/a682231.html',
    'Drug Name: Phenazopyridine, Link: https://medlineplus.gov/druginfo/meds/a682231.html',
    'Drug Name: Phenazopyridine, Link: https://medlineplus.gov/druginfo/meds/a682231.html',
    'Drug Name: Brinzolamide Ophthalmic, Link: https://medlineplus.gov/druginfo/meds/a601233.html',
    'Drug Name: Olmesartan, Link: https://medlineplus.gov/druginfo/meds/a603006.html',
    'Drug Name: Amlodipine, Link: https://medlineplus.gov/druginfo/meds/a692044.html',
    'Drug Name: Serdexmethylphenidate and Dexmethylphenidate, Link: https://medlineplus.gov/druginfo/meds/a621026.html',
    'Drug Name: Zidovudine Injection, Link: https://medlineplus.gov/druginfo/meds/a601168.html',
    'Drug Name: Zidovudine, Link: https://medlineplus.gov/druginfo/meds/a687007.html',
    'Drug Name: Aztreonam Injection, Link: https://medlineplus.gov/druginfo/meds/a687010.html',
    'Drug Name: Sulfasalazine, Link: https://medlineplus.gov/druginfo/meds/a682204.html',
    'Drug Name: Sulfasalazine, Link: https://medlineplus.gov/druginfo/meds/a682204.html',
    'Drug Name: Estrogen and Progestin (Oral Contraceptives), Link: https://medlineplus.gov/druginfo/meds/a601050.html',
]
